### ISSUE TITLE
Create year folders in tmp

### ISSUE THREAD

**Issue by tomguanzi** [rdahis/clean_RAIS#1]
The code in "src\sub\####.do" saves a file in  "tmp/####/`state'.dta"

But there is no such folder. 
You can either manually create those folders or add the following piece of code in each year do file:

cap mkdir  "tmp/####"

where #### corresponds to the year

**Comment by rdahis** [comment]
Now we have a `tmp/.gitkeep` file to keep the `tmp` folder in the repository ;-)
