### ISSUE TITLE
Error trying to query data from R:  Access Denied

### ISSUE THREAD

**Issue by jjesusfilho** [rdahis/clean_RAIS#4]
I am new to bigrquery. I followed [this instructions](https://basedosdados.github.io/mais/access_data_local/) to query the data from the database and got the following error:

```Error: Access Denied: Project basedosdados: User does not have bigquery.jobs.create permission in project basedosdados. [accessDenied] ```

**Comment by jjesusfilho** [comment]
I got it. This is an example of the proper way to query from R:

```
library("bigrquery")
bq_auth()
project_id = "tidy-alchemy-286700"

vinculos_rais_municipio = "SELECT *
FROM `basedosdados.br_me_rais.agregado_vinculos_municipio` limit 100"

d <- bq_table_download(bq_project_query(project_id, vinculos_rais_municipio))
```

**Comment by rdahis** [comment]
Great! Thanks for pointing it out. We are rewriting code to provide a clearer error message in authentication errors like this.
